import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Shell } from "@/components/shell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <div className="min-h-screen bg-background">
          <SidebarProvider
            style={
              {
                "--sidebar-width": "20rem",
              } as React.CSSProperties
            }
          >
            <Shell>{children}</Shell>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
